# Generated by Django 4.0.5 on 2022-06-04 18:44

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations


def create_user(username: str, password: str):
    user = User.objects.filter(username=username).first()
    if user:
        user.set_password(password)
        user.save()
    else:
        User.objects.create_superuser(
            username=username,
            email=f'{username}@storage.com',
            password=password
        )


def create_initial_users(apps, schema_editor):
    create_user('user1', '123456')
    create_user('user2', '123456')
    create_user('user3', '123456')
    create_user('user4', '123456')
    create_user('user5', '123456')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_initial_users)
    ]
