# Generated by Django 4.0.5 on 2022-06-05 23:23

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('path', models.CharField(db_column='tx_path', max_length=256, verbose_name='Path')),
                ('file', models.FileField(upload_to=core.models.get_upload_path, verbose_name='File')),
                ('full_path', models.CharField(blank=True, db_column='tx_full_path', max_length=256, null=True, verbose_name='Full path')),
                ('file_name', models.CharField(blank=True, db_column='tx_file_name', max_length=256, null=True, verbose_name='File name')),
                ('revision', models.IntegerField(blank=True, db_column='nb_revision', null=True, verbose_name='Revision')),
                ('current_revision', models.BooleanField(blank=True, db_column='cs_current_revision', default=False, null=True, verbose_name='Current revision')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='dt_uploaded', null=True, verbose_name='Uploaded at')),
                ('user', models.ForeignKey(db_column='id_user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
            },
        ),
    ]
