# Generated by Django 4.0.5 on 2022-06-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_creating_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='full_path',
        ),
    ]
