# Generated by Django 4.0.5 on 2022-06-08 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_document_full_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='current_revision',
        ),
        migrations.AlterField(
            model_name='document',
            name='revision',
            field=models.IntegerField(db_column='nb_revision', default=0, verbose_name='Revision'),
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('revision', models.IntegerField(db_column='nb_revision', verbose_name='Revision')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('file_name', models.CharField(blank=True, db_column='tx_file_name', max_length=256, null=True, verbose_name='File name')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='dt_uploaded', null=True, verbose_name='Uploaded at')),
                ('document', models.ForeignKey(db_column='id_document', on_delete=django.db.models.deletion.CASCADE, related_name='document_revisions', to='core.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Document revision',
                'verbose_name_plural': 'Document revisions',
                'db_table': 'document_revision',
            },
        ),
    ]
